spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/reserve
        username: root
        password: 1234
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:
            maximum-pool-size: 10 # ?? ?? ? ?? (??)
    jpa:
        hibernate:
            ddl-auto: update # ?????? ?? ???? ?? (?: update, create, validate)
        show-sql: true # ???? SQL? ??? ??
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true


